name: Deploy
on:
  push:
    tags: ['v*']

jobs:
  deploy:
    name: Deploy
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Deploy release
        run: ./gradlew -Dorg.gradle.parallel=true publish --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_leavesmcUsername: ${{ secrets.NEW_REPO_USERNAME }}
          ORG_GRADLE_PROJECT_leavesmcPassword: ${{ secrets.NEW_REPO_PASSWORD }}
